# Generated by Django 5.0.2 on 2024-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurements',
            field=models.FloatField(),
        ),
    ]
