# Generated by Django 5.0.2 on 2024-02-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_measurements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurements',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='id_sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
